name: Django CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Remove conflicting packages
      run: |
        sudo apt-get purge -y containerd containerd.io docker.io
        sudo apt-get autoremove -y
        sudo apt-get clean

    - name: Install Docker using official script
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        rm get-docker.sh
        docker --version

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and Run Docker Containers
      run: |
        docker-compose -f docker-compose.yml up --build -d
        docker ps

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install coverage
      run: |
        pip install coverage

    - name: Run Tests with Coverage
      run: |
        coverage run manage.py test  # Ejecuta los tests con coverage
        coverage report  # Muestra un reporte de cobertura en la terminal

    - name: Generate Coverage HTML Report
      run: |
        coverage html  # Crea un reporte en HTML

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/  # Subir el reporte HTML generado
